config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView, TemplateView
from django_otp.admin import OTPAdminSite
from users.models import User
from django.contrib.sitemaps.views import sitemap
from sayches.subsections.sitemaps import HomeStaticViewSitemap
from sayches.users.sitemaps import UserProfileStaticViewSitemap
from django.views.static import serve
import os
from rest_framework.authtoken.views import obtain_auth_token
from sayches.subsections.rss import NewsroomFeed

class OTPAdmin(OTPAdminSite):
    pass

from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")}, name="404"
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


sitemaps = {
            "home_static": HomeStaticViewSitemap,
            "users_static":UserProfileStaticViewSitemap,
            }

ADMIN_URL = os.environ.get('ADMIN_PATH')

urlpatterns += [
                   path("", include("subsections.urls", namespace="subsections")),
                   path("", RedirectView.as_view(pattern_name='subsections:home', permanent=False)),
                   path(ADMIN_URL, admin.site.urls),
                   path("", include("sign.urls")),
                   path("", include("users.urls", namespace="profile")),
                   path("", include("posts.urls", namespace="posts")),
                   path("", include("ads.urls", namespace="ads")),
                   path("messages/", include("message.urls", namespace="message")),
                   path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                   path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
                   path("api/", include("api.urls")),
                   path('auth/', obtain_auth_token),
                   path('newsroom/rss/', NewsroomFeed()),
]

DEBUG = os.environ.get('DEBUG')

if eval(DEBUG) == False:
    admin.site.__class__ = OTPAdminSite
admin.site.site_header = "Administration Area"
admin.site.site_title = "Sayches Admin Portal"
handler404 = 'sayches.custom_views.handler404'

sayches/ads/urls.py
from django.urls import path

from . import views

app_name = "ads"

urlpatterns = [
    path("ads/invoice/<str:invoice_number>", views.ad_invoice, name="ad-invoice"),
    path("ad_click/<str:slug>", views.ad_clicks, name="ad_click"),
]

sayches/api/urls.py
from django.conf import settings
from django.urls import path, include
from rest_framework import routers

from .views import *

if settings.DEBUG:
    router = routers.DefaultRouter()
else:
    router = routers.SimpleRouter()

############# # Post APIs # #############
router.register('post', PublicPostViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

sayches/message/urls.py
from django.urls import path

from . import views

app_name = "message"

urlpatterns = [
    path("", views.chat_inbox, name="inbox"),
    path("inbox/delete/<int:id>/", views.delete_chat, name="delete_chat"),
    path("create_message/", views.create_messages, name="create_message"),
    path("chat_data/", views.chat_data, name="chat_data"),
    path("chat_header_data/", views.chat_header_data, name="chat_header_data"),
    path("chat_content_data/", views.old_messages_content_data, name="old_messages_content_data"),
    path("ad_chat_content_data/", views.admin_messages_content_data, name="admin_messages_content_data"),
    path("new_messages_content_data/", views.new_messages_content_data, name="new_messages_content_data"),
    path("search-users-and-chats/", views.search_for_users_and_chats, name="search-users-and-chats"),
    path("chat/<str:username>/", views.start_chat_with_user, name="chat-specfic-user"),
    path("user/json/<str:username>/", views.get_json_user, name="get-json-user"),

]

sayches/sign/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.user_login, name='login'),
    path('steps_form/', views.steps_form, name='steps_form'),
    path('logout/', views.logout_view, name='logout'),
]

sayches/subsections/urls.py
from django.urls import path

from . import views

app_name = "subsections"

urlpatterns = [
    path("feed", views.home, name="home"),
    path("docs/", views.docs, name="docs"),
    path("docs/<str:slug>", views.single_docs, name="single_docs"),
    path("newsroom", views.newsroom, name="news"),
    path("newsroom/<str:slug>", views.article, name="article"),
    path("help", views.help, name="help"),
    path("remove_alert", views.remove_alert, name="remove_alert"),
    path('ads/', views.ads_step_one, name="ads"),
    path('ads/design/<str:ads_slug>/', views.ads_step_two, name="ads-step-two"),
    path('ads/plan/<str:ads_slug>/', views.ads_step_three, name="ads-step-three"),
    path('ads/checkout/<str:ads_slug>/', views.ads_step_four, name="ads-step-four"),
]

sayches/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('<int:id>/', views.profile_detail, name="profile"),
    path('settings', views.profile_update, name="profile_update"),
    path('update/nick', views.UpdateNickView.as_view(), name="profile_nickname"),
    path('update/toggle', views.UpdateToggleView.as_view(), name="profile_toggles"),
    path('u/<str:username>', views.profile_detail_name, name="profile_name"),
    path('forget/<str:username>', views.forget_user, name='forget-user'),
    path('set-or-remove-bell/<str:username>/', views.set_or_remove_bell_for_user, name="set-or-remove-bell"),
    path('ping-user/<str:username>', views.ping_user, name="ping-user"),
    path('pong-user/<int:id>/', views.pong_user, name="pong-user"),
    path('report_user', views.report_user, name="report_user"),
    path("notifications/notifications_counter", views.notification_number, name="notification_number"),
    path("notifications/mark_all", views.mark_all_read, name="mark_all_read"),
    path("notifications/notify_read", views.notify_read, name="notify_read"),
    path("notifications/admin_notify_read", views.admin_notify_read, name="admin_notify_read"),
    path("notifications/notifications_reload/", views.notifications_reload, name="notifications_reload"),
    path("export/<str:username>", views.export_my_data, name="export_my_data"),
    path('search/user', views.search_user, name='search-user'),
]

sayches/message/forms.py
from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']


class MessageFromProfile(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']

sayches/ads/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from subsections.models import Ads

from .models import CreateAds, Vouchers


def targeted_ads(request):
    ad = CreateAds.objects.filter(Q(location=request.user.country) |
                                  Q(target_all_users=True) |
                                  Q(target_user_list=request.user)).order_by('?').first()
    return ad


@login_required
def ad_invoice(request, invoice_number):
    ads = Ads.objects.get(slug=invoice_number)
    try:
        ads_owner = Ads.objects.get(user=request.user)
    except:
        ads_owner = None
    if request.user != ads.user:
        return redirect('subsections:home')
    context = {
        "ads": ads,
        "ads_owner": ads_owner,
    }
    return render(request, 'ads/invoice.html', context)


def voucher_discount(voucher, ads):
    discount_percentage = voucher.discount_percentage
    discount_amount = discount_percentage / 100 * ads.ad_price
    amount_due = ads.ad_price - discount_amount
    ads.amount_due = amount_due
    ads.discount_amount = discount_amount
    ads.discount = discount_percentage
    ads.save()
    return discount_percentage, amount_due


def ad_period(ads):
    start_date = ads.ad_start_date
    end_date = ads.ad_end_date
    number_of_days = (end_date - start_date).days
    return number_of_days


def ad_clicks(request, slug):
    if request.is_ajax():
        try:
            ad = Ads.objects.get(status="1", slug=slug)
            ad.clicks.add(request.user)
            ad.save()
        except:
            return JsonResponse({'success': 'false'})
        return JsonResponse({'success': 'true'})
    return HttpResponseBadRequest()


def validate_voucher(voucher_code, user, ad_plan):
    if not voucher_code:
        return
    vouchers = Vouchers.objects.filter(voucher_code=voucher_code, expired=False)

    if not vouchers.exists():
        return False

    voucher = vouchers.first()
    try:
        if voucher.end_date <= datetime.date.today():
            vouchers.update(expired=True)
    except:
        pass

    if voucher.is_expired or not voucher.is_valid(user, ad_plan):
        return False

    return voucher

sayches/api/views.py
from posts.models import Post
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .serializers import *


############# # Post APIs # #############


class PublicPostViewSet(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    serializer_class = PublicPostSerializer
    queryset = Post.objects.all()
    http_method_names = ['get']
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        queryset = Post.objects.filter(user=self.request.user)
        return queryset

sayches/sign/views.py
from datetime import timedelta, datetime

import requests
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from message.crypto import MessagingRSA
from rest_framework.authtoken.models import Token
from sign.utils import token_expire_handler
from subsections.views import get_bitcoin_address
from sudo.models import CloseRegistration
from users.models import BlacklistUser
from users.models import Profile
from users.models import User

from .forms import UserRegistrationForm, UserLoginForm, StepsForm


@require_http_methods(["GET", "POST"])
def signup(request):
    if (request.user.is_authenticated):
        return redirect(reverse('subsections:home'))
    error = ''
    success = ''
    flag = "false"
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid():
            cd = user_form.cleaned_data
            new_user = user_form.save(commit=False)
            new_user.username = cd['user_hash']
            new_user.set_password(cd['password'])
            new_user.first_login = True
            new_user.is_active = True
            if cd['disposable']:
                new_user.disposable = True
            new_user.save()
            Profile.objects.create(user=new_user)
            user = authenticate(request, username=cd['user_hash'], password=cd['password'])
            login(request, user)
            token, created = Token.objects.get_or_create(user=user)
            token_expire_handler(request)
            request.session['encryption_token'] = cd['password']
            request.session.modified = True
            MessagingRSA.create_rsa(request)
            if user.first_login:
                response = redirect(reverse('steps_form'))
                return response
            return redirect(reverse('login'), {'new_user': new_user})
        else:
            flag = "true"
    else:
        user_form = UserRegistrationForm()

    sayches_customization = CloseRegistration.objects.filter(close_registration=True).first()
    return render(request, 'account/signup.html', {'user_form': user_form,
                                                   'flag': flag,
                                                   'sayches_customization': sayches_customization,
                                                   'messages': {'error': error, 'sucesss': success}})


@require_http_methods(["GET", "POST"])
def user_login(request):
    remember_me_data = {
        "password": request.COOKIES.get('password'),
        "username": request.COOKIES.get('username')
    }
    if (request.user.is_authenticated):
        return redirect(reverse('subsections:home'))
    error = ''
    flag = "false"
    if request.method == 'POST':
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data

            user = authenticate(request, username=cd['login'], password=cd['password'])
            if user is None:
                user = authenticate(request, username=cd['login'], password=cd['password'])

            if user:
                if user.is_active:
                    check_black_list = BlacklistUser.objects.filter(user=user, on_login=True).first()
                    if not check_black_list:
                        login(request, user)
                        token, created = Token.objects.get_or_create(user=user)
                        token_expire_handler(request)
                        request.session['encryption_token'] = cd['password']
                        request.session.modified = True
                        MessagingRSA.create_rsa(request)
                        response = redirect(reverse('subsections:home'))
                        if user.first_login:
                            response = redirect(reverse('steps_form'))

                        if cd['remember_me']:
                            response.set_cookie('password', cd['password'])
                            response.set_cookie('username', cd['login'])

                        if user.first_login:
                            return response
                        return response
                    else:
                        error = 'Sayches suspends accounts which violate the Sayches Rules'
                        flag = "true"
                else:
                    error = 'Disabled account'
            else:
                error = 'Username or password does not match'
                flag = "true"
        else:
            error = 'Fill the username and password'
    else:
        login_form = UserLoginForm()
    return render(request, 'account/login.html',
                  {'form': login_form, 'error': error, "flag": flag, "remember_me_data": remember_me_data})

@login_required
@require_http_methods(["GET", "POST"])
def steps_form(request):
    user = request.user
    if not (user.first_login):
        return redirect(reverse('subsections:home'))
    profile = user.profile
    initial_dic = {}
    errors = ''

    if user.name:
        initial_dic['name'] = user.name

    if user.country:
        initial_dic['country'] = user.country.name

    if request.method == 'POST':
        steps_form = StepsForm(data=request.POST, files=request.FILES)

        if steps_form.is_valid():
            cd = steps_form.cleaned_data

            user.alias = cd['alias']
            user.country = request.POST.get('location')
            user.first_login = False
            user.save()

            if cd['image']:
                profile = Profile.objects.get(user=user)
                profile.photo = cd['image']
            profile.save()
            return redirect(reverse('subsections:home'))


        else:
            for error in steps_form.errors:
                errors += error

    else:
        steps_form = StepsForm(initial=initial_dic)

    context = {'steps_form': steps_form, 'bitcoin_address': get_bitcoin_address, "errors": errors}
    return render(request, 'account/steps_form/steps_form.html', context)


@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('subsections:home')
    return render(request, 'account/logout.html')

sayches/templates/base/header/backbtn.html
{% load static %}
<div class="logo-box " onclick="goBack()">
   <i class="ri-arrow-left-line primary-colour header-icon"></i>
</div>

sayches/templates/base/header/dropdown.html
{% load static %}
<div class="authenticated-user-img dropdown">
   <div class="noti-box2">
      <a class="img-icon noti2-click" href="#">
      <img src="{{ request.user.profile.photo_url }}" alt="Profile Picture">
      </a>
      <div class="notification-dropdown2">
         <div class="notification-content">
            <a class="dropdown-item" href="{% url 'users:profile_name' request.user.user_hash %}">
            <i class="ri-user-line primary-colour pr-4"></i>
            Profile
            </a>
            <a class="dropdown-item" href="{% url 'users:profile_update' %}">
            <i class="ri-settings-5-line primary-colour pr-4"></i>
            Settings
            </a>
            <a class="dropdown-item" href="{% url 'logout' %}">
            <i class="ri-shut-down-line primary-colour pr-4"></i>
            Log out
            </a>
         </div>
      </div>
   </div>
</div>

sayches/templates/base/header/header.html
{% load static %}
<header>
   {%include 'base/reminders.html'%}
   <div class="custom-nav landing">
      <div class="container">
         <div class="row">
            <div class="col-md-6 col-4">
               <div class="nav-box">
                  <div class="logo-box">
                     <a href="{% url 'subsections:home' %}">
                     <img src="{% static 'assets/images/saychesLogo/sayches_271x271.svg' %}" alt="Sayches Logo" class="img-fluid">
                     </a>
                     {% if show_beta_icon %}
                     <span class="beta-icon">BETA</span>
                     {% endif %}
                  </div>
                  {%if backbtn %}
                  {%include 'base/header/backbtn.html'%}
                  {%endif%}
                  <div class="custom-search dropdown">
                     <img src="{% static 'assets/images/icons/svgIcons/close_100x100.svg' %}" alt="Close" class="custom-ex">
                     <form action="{% url 'posts:search' %}">
                        <div class="search-box">
                           <input type="text" placeholder="SEARCH OR JUMP TO..." name="search" id="search">
                           <button type="button" data-toggle="dropdown" id="dropdownMenuButton">
                           <button type="submit">
                           <i class="ri-search-line primary-colour header-icon img-fluid"></i>
                           </button>
                           <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="search_ops">
                           </ul>
                        </div>
                     </form>
                  </div>
                  <div class="mob-search">
                     <img src="{% static 'assets/images/icons/svgIcons/search_100x100.svg' %}" alt="Search">
                  </div>
               </div>
            </div>
            <div class="col-md-6 col-8">
               {% if request.user.is_authenticated %}
               <div class="authenticated-user-box">
                  {% if request.path == "/" %}
                  <a href="{% url 'subsections:home' %}" class="primary-button">Feed</a>
                  {% else %}
                  <div class="authenticated-user-list">
                     <ul id="header_reload">
                        {% include 'base/header/notifications.html' %}
                     </ul>
                  </div>
                  {% if request.user.profile %}
                  {%include 'base/header/dropdown.html'%}
                  {% endif %}
                  {% endif %}
               </div>
               {% else %}
               <div class="authenticated-user-box">
                  <div class="btns-container">
                     {% if not request.user.is_authenticated %}
                     <a href="{% url 'signup' %}" class="primary-button">Sign up</a>
                     <a href="{% url 'login' %}" class="primary-button">Login</a>
                     {% endif %}
                  </div>
               </div>
               {% endif %}
            </div>
         </div>
      </div>
   </div>
</header>
<script type="text/javascript"  src="{%static 'lib/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/header.js' %}"></script>
<script src="{% static 'assets/js/mobile-search.js' %}"></script>
<script>
   setInterval(function () {
     $.ajax({
       type: 'Post',
       url: notificationsReload,
       data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
       success: function (data) {
         $('#header_reload').html(data);
       }
     });
   }, 30 * 1000);
   var pongUser = "{% url 'users:pong-user' id=9999 %}";
   var notificationsReload = "{% url 'users:notifications_reload' %}";
</script>

sayches/templates/base/header/menu.html
{% load static %}
<div class="authenticated-user-img dropdown">
   <div class="noti-box2">
      <a class="img-icon noti2-click" href="#">
      <img src="{{ request.user.profile.photo_url }}" alt="Profile Picture">
      </a>
      <div class="notification-dropdown2">
         <div class="notification-content">
            <a class="dropdown-item" href="{% url 'users:profile_name' request.user.user_hash %}">
            <i class="ri-user-line primary-colour pr-4"></i>
            Profile
            </a>
            <a class="dropdown-item" href="{% url 'users:profile_update' %}">
            <i class="ri-settings-5-line primary-colour pr-4"></i>
            Settings
            </a>
            <a class="dropdown-item" href="#">
            <i class="ri-shut-down-line primary-colour pr-4"></i>
            Log out
            </a>
         </div>
      </div>
   </div>
</div>

sayches/templates/base/header/notifications.html
{% load static %}
<ul>
   <li>
      <a href="{% url 'subsections:help' %}"><i class="ri-question-line primary-colour header-icon"></i></a>
   </li>
   <li>
      <a href="{% url 'message:inbox' %}">
         <i class="ri-mail-line primary-colour header-icon"></i>
         <div class="noti-box">
            {% if user_unread_chats_count > 0 %}
            <span class="num-noti msg-noti parag" id="">{{ user_unread_chats_count }}</span>
            {% endif %}
         </div>
      </a>
   </li>

   <li>
      <div id="notifications_reload">
      <div class="noti-box">
      <i class="ri-notification-3-line noti-click primary-colour header-icon"></i>
      {% if nfs_count > 0 %}
      <span class="num-noti parag noti-click">{{ nfs_count }}</span>
      {% endif %}
      <div class="notification-dropdown">
      <div class="box-header">
         <p class="parag header-p"></p>
         <p class="parag mark-p"><a href="#" onclick='markAllAsRead(event)'>Mark All As Read</a></p>
      </div>
      <div class="notification-content">
      <h3 class="new-h after-border">New</h3>
      {% if not_notification_follower %}
      {% for adnf in not_notification_follower %}
      <div class="box-item after-border admin-notifi" admin-notify-id="{{ adnf.id }}">
         <a href="{{ adnf.nf_url }}" class="overlay-link"></a>
         <div class="txt-box custom-unread">
            <p class="parag txt-hint">{{ adnf.nf_title }}<span>{{ adnf.created_at.date }}</span></p>
            <p class="parag txt-p"><span>{{ adnf.nf_description }}</span></p>
         </div>
         <div class="img-box">
            <img alt="Profile Picture" src="{{ adnf.user.uprofile.photo_url }}">
         </div>
      </div>
      {% endfor %}
      {% endif %}
      {% if notification_follower %}
      <div class="box-item after-border admin-notifi" admin-notify-id="{{ notification_follower.id }}">
         <a href="{{ notification_follower.nf_url }}" class="overlay-link"></a>
         <div class="txt-box">
            <p class="parag txt-hint">{{ notification_follower.nf_title }}<span>{{ notification_follower.created_at.date }}</span></p>
            <p class="parag txt-p">{{ notification_follower.nf_description }}</p>
         </div>
      </div>
      {% endif %}
      {% if nfs_after_ajax %}
      {% for nf in nfs_after_ajax %}
      {% if nf.read == False %}
      {% if nf.activity_type == "bell" %}
      <div notify-id="{{ nf.id }}" class="box-item fav-box after-border custom-unread">
      {% elif nf.activity_type == "ping" %}
      <div notify-id="{{ nf.id }}" class="box-item after-border custom-unread ping-pong">
         {% else %}
         <div notify-id="{{ nf.id }}" class="box-item after-border custom-unread ">
            {% endif %}
            {% else %}
            {% if nf.activity_type == "bell" %}
            <div notify-id="{{ nf.id }}" class="box-item fav-box after-border">
               {% elif nf.activity_type == "ping" %}
               <div notify-id="{{ nf.id }}" class="box-item after-border ping-pong">
                  {% else %}
                  <div class="box-item after-border" notify-id="{{ nf.id }}">
                     {% endif %}
                     {% endif %}
                     {% if nf.activity_type == "bell" %}
                     <a href="{{ nf.target.pinger_user.get_absolute_url }}"></a>
                     {% else %}
                     {% endif %}
                     <div class="txt-box">
                        <a {% if nf.target_id is not None and nf.activity_type != 'ping' and nf.activity_type != 'bell' and nf.activity_type != 'pong' %}
                        href = "{% url 'posts:post_detail' nf.target_id %}"
                        {% elif nf.sender  and nf.activity_type == 'bell' %}
                        href = "{% url 'posts:post_detail' nf.target_id %}"
                        {% elif nf.sender or nf.activity_type == 'ping' %}
                        href = "{% url 'users:profile_name' nf.sender %}"
                        {% endif %} >
                        <p class="parag txt-hint">Notification<span>{{ nf.created_at.date }}</span></p>
                        <p class="parag txt-p">
                           {% if nf.anonymous_user %}
                           <span>{{ nf.anonymous_user }}</span>
                           {% elif nf.sender == None %}
                           {% else %}
                           {% if request.user.is_authenticated %}
                           <span>{{ nf.sender }}</span>
                           {% else %}
                           <span>{% if nf.target.get_mood_display %}{{ nf.target.get_mood_display }} {% else %}
                           {{ nf.target.pinger_user.username }} {% endif %}</span>
                           {% endif %}
                           {% endif %}
                           {{ nf.verb }}
                        </p>
                        </a>
                     </div>
                     {% if nf.anonymous_user %}
                     <div class="img-box">
                        <img alt="Anonymous" src="{% static 'assets/images/avatars/incognitoAvatar/incognitoAvatar_360x360.png' %}">
                     </div>
                     {% elif nf.sender.profile %}
                     {% if nf.sender.profile.photo %}
                     <div class="img-box">
                        {% if nf.activity_type == "ping" %}
                        {% with username=nf.target.pinger_user.username %}
                        {% with id=nf.target.id %}
                        <a class="pong-btn" id="pong-btn" {% if nf.target.pong %}disabled style="background: black;color: white; cursor: pointer" href="#"{% else %} style="cursor: pointer" onclick='pong_user("{{ id }}", this)' {% endif %} > Pong </a>
                        {% endwith %}
                        {% endwith %}
                        <img alt="Profile Picture" src="{{ nf.sender.profile.photo_url }}">
                        {% else %}
                        <img alt="Profile Picture" src="{{ nf.sender.profile.photo_url }}">
                        {% endif %}
                     </div>
                     {% else %}
                     <div class="img-box">
                        {% if nf.activity_type == "ping" %}
                        {% with id=nf.target.id %}
                        <a class="pong-btn" id="pong-btn" {% if nf.target.pong %}disabled style="background: black;color: white; cursor: pointer" href="#"{% else %} style="cursor: pointer" onclick='pong_user("{{ id }}", this)' {% endif %} > Pong </a>
                        {% endwith %}
                        {% endif %}
                        <img alt="Profile Picture" src="{{ nf.sender.profile.photo_url }}">
                     </div>
                     {% endif %}
                     {% endif %}
                  </div>
                  {% endfor %}
                  {% endif %}
               </div>
            </div>
         </div>
      </div>
   </li>
</ul>
<script src="{% static 'assets/js/notifications.js' %}"></script>