config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView, TemplateView
from django_otp.admin import OTPAdminSite
from users.models import User
from django.contrib.sitemaps.views import sitemap
from sayches.subsections.sitemaps import HomeStaticViewSitemap
from sayches.users.sitemaps import UserProfileStaticViewSitemap
from django.views.static import serve
import os
from rest_framework.authtoken.views import obtain_auth_token
from sayches.subsections.rss import NewsroomFeed

class OTPAdmin(OTPAdminSite):
    pass

from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")}, name="404"
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


sitemaps = {
            "home_static": HomeStaticViewSitemap,
            "users_static":UserProfileStaticViewSitemap,
            }

ADMIN_URL = os.environ.get('ADMIN_PATH')

urlpatterns += [
                   path("", include("subsections.urls", namespace="subsections")),
                   path("", RedirectView.as_view(pattern_name='subsections:home', permanent=False)),
                   path(ADMIN_URL, admin.site.urls),
                   path("", include("sign.urls")),
                   path("", include("users.urls", namespace="profile")),
                   path("", include("posts.urls", namespace="posts")),
                   path("", include("ads.urls", namespace="ads")),
                   path("messages/", include("message.urls", namespace="message")),
                   path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                   path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
                   path("api/", include("api.urls")),
                   path('auth/', obtain_auth_token),
                   path('newsroom/rss/', NewsroomFeed()),
]

DEBUG = os.environ.get('DEBUG')

if eval(DEBUG) == False:
    admin.site.__class__ = OTPAdminSite
admin.site.site_header = "Administration Area"
admin.site.site_title = "Sayches Admin Portal"
handler404 = 'sayches.custom_views.handler404'

sayches/ads/urls.py
from django.urls import path

from . import views

app_name = "ads"

urlpatterns = [
    path("ads/invoice/<str:invoice_number>", views.ad_invoice, name="ad-invoice"),
    path("ad_click/<str:slug>", views.ad_clicks, name="ad_click"),
]

sayches/api/urls.py
from django.conf import settings
from django.urls import path, include
from rest_framework import routers

from .views import *

if settings.DEBUG:
    router = routers.DefaultRouter()
else:
    router = routers.SimpleRouter()

############# # Post APIs # #############
router.register('post', PublicPostViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

sayches/message/urls.py
from django.urls import path

from . import views

app_name = "message"

urlpatterns = [
    path("", views.chat_inbox, name="inbox"),
    path("inbox/delete/<int:id>/", views.delete_chat, name="delete_chat"),
    path("create_message/", views.create_messages, name="create_message"),
    path("chat_data/", views.chat_data, name="chat_data"),
    path("chat_header_data/", views.chat_header_data, name="chat_header_data"),
    path("chat_content_data/", views.old_messages_content_data, name="old_messages_content_data"),
    path("ad_chat_content_data/", views.admin_messages_content_data, name="admin_messages_content_data"),
    path("new_messages_content_data/", views.new_messages_content_data, name="new_messages_content_data"),
    path("search-users-and-chats/", views.search_for_users_and_chats, name="search-users-and-chats"),
    path("chat/<str:username>/", views.start_chat_with_user, name="chat-specfic-user"),
    path("user/json/<str:username>/", views.get_json_user, name="get-json-user"),

]

sayches/sign/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.user_login, name='login'),
    path('steps_form/', views.steps_form, name='steps_form'),
    path('logout/', views.logout_view, name='logout'),
]

sayches/subsections/urls.py
from django.urls import path

from . import views

app_name = "subsections"

urlpatterns = [
    path("feed", views.home, name="home"),
    path("docs/", views.docs, name="docs"),
    path("docs/<str:slug>", views.single_docs, name="single_docs"),
    path("newsroom", views.newsroom, name="news"),
    path("newsroom/<str:slug>", views.article, name="article"),
    path("help", views.help, name="help"),
    path("remove_alert", views.remove_alert, name="remove_alert"),
    path('ads/', views.ads_step_one, name="ads"),
    path('ads/design/<str:ads_slug>/', views.ads_step_two, name="ads-step-two"),
    path('ads/plan/<str:ads_slug>/', views.ads_step_three, name="ads-step-three"),
    path('ads/checkout/<str:ads_slug>/', views.ads_step_four, name="ads-step-four"),
]

sayches/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('<int:id>/', views.profile_detail, name="profile"),
    path('settings', views.profile_update, name="profile_update"),
    path('update/nick', views.UpdateNickView.as_view(), name="profile_nickname"),
    path('update/toggle', views.UpdateToggleView.as_view(), name="profile_toggles"),
    path('u/<str:username>', views.profile_detail_name, name="profile_name"),
    path('forget/<str:username>', views.forget_user, name='forget-user'),
    path('set-or-remove-bell/<str:username>/', views.set_or_remove_bell_for_user, name="set-or-remove-bell"),
    path('ping-user/<str:username>', views.ping_user, name="ping-user"),
    path('pong-user/<int:id>/', views.pong_user, name="pong-user"),
    path('report_user', views.report_user, name="report_user"),
    path("notifications/notifications_counter", views.notification_number, name="notification_number"),
    path("notifications/mark_all", views.mark_all_read, name="mark_all_read"),
    path("notifications/notify_read", views.notify_read, name="notify_read"),
    path("notifications/admin_notify_read", views.admin_notify_read, name="admin_notify_read"),
    path("notifications/notifications_reload/", views.notifications_reload, name="notifications_reload"),
    path("export/<str:username>", views.export_my_data, name="export_my_data"),
    path('search/user', views.search_user, name='search-user'),
]

sayches/message/forms.py
from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']


class MessageFromProfile(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']

sayches/ads/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from subsections.models import Ads

from .models import CreateAds, Vouchers


def targeted_ads(request):
    ad = CreateAds.objects.filter(Q(location=request.user.country) |
                                  Q(target_all_users=True) |
                                  Q(target_user_list=request.user)).order_by('?').first()
    return ad


@login_required
def ad_invoice(request, invoice_number):
    ads = Ads.objects.get(slug=invoice_number)
    try:
        ads_owner = Ads.objects.get(user=request.user)
    except:
        ads_owner = None
    if request.user != ads.user:
        return redirect('subsections:home')
    context = {
        "ads": ads,
        "ads_owner": ads_owner,
    }
    return render(request, 'ads/invoice.html', context)


def voucher_discount(voucher, ads):
    discount_percentage = voucher.discount_percentage
    discount_amount = discount_percentage / 100 * ads.ad_price
    amount_due = ads.ad_price - discount_amount
    ads.amount_due = amount_due
    ads.discount_amount = discount_amount
    ads.discount = discount_percentage
    ads.save()
    return discount_percentage, amount_due


def ad_period(ads):
    start_date = ads.ad_start_date
    end_date = ads.ad_end_date
    number_of_days = (end_date - start_date).days
    return number_of_days


def ad_clicks(request, slug):
    if request.is_ajax():
        try:
            ad = Ads.objects.get(status="1", slug=slug)
            ad.clicks.add(request.user)
            ad.save()
        except:
            return JsonResponse({'success': 'false'})
        return JsonResponse({'success': 'true'})
    return HttpResponseBadRequest()


def validate_voucher(voucher_code, user, ad_plan):
    if not voucher_code:
        return
    vouchers = Vouchers.objects.filter(voucher_code=voucher_code, expired=False)

    if not vouchers.exists():
        return False

    voucher = vouchers.first()
    try:
        if voucher.end_date <= datetime.date.today():
            vouchers.update(expired=True)
    except:
        pass

    if voucher.is_expired or not voucher.is_valid(user, ad_plan):
        return False

    return voucher

sayches/api/views.py
from posts.models import Post
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .serializers import *


############# # Post APIs # #############


class PublicPostViewSet(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    serializer_class = PublicPostSerializer
    queryset = Post.objects.all()
    http_method_names = ['get']
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        queryset = Post.objects.filter(user=self.request.user)
        return queryset

sayches/sign/views.py
from datetime import timedelta, datetime

import requests
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from message.crypto import MessagingRSA
from rest_framework.authtoken.models import Token
from sign.utils import token_expire_handler
from subsections.views import get_bitcoin_address
from sudo.models import CloseRegistration
from users.models import BlacklistUser
from users.models import Profile
from users.models import User

from .forms import UserRegistrationForm, UserLoginForm, StepsForm


@require_http_methods(["GET", "POST"])
def signup(request):
    if (request.user.is_authenticated):
        return redirect(reverse('subsections:home'))
    error = ''
    success = ''
    flag = "false"
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid():
            cd = user_form.cleaned_data
            new_user = user_form.save(commit=False)
            new_user.username = cd['user_hash']
            new_user.set_password(cd['password'])
            new_user.first_login = True
            new_user.is_active = True
            if cd['disposable']:
                new_user.disposable = True
            new_user.save()
            Profile.objects.create(user=new_user)
            user = authenticate(request, username=cd['user_hash'], password=cd['password'])
            login(request, user)
            token, created = Token.objects.get_or_create(user=user)
            token_expire_handler(request)
            request.session['encryption_token'] = cd['password']
            request.session.modified = True
            MessagingRSA.create_rsa(request)
            if user.first_login:
                response = redirect(reverse('steps_form'))
                return response
            return redirect(reverse('login'), {'new_user': new_user})
        else:
            flag = "true"
    else:
        user_form = UserRegistrationForm()

    sayches_customization = CloseRegistration.objects.filter(close_registration=True).first()
    return render(request, 'account/signup.html', {'user_form': user_form,
                                                   'flag': flag,
                                                   'sayches_customization': sayches_customization,
                                                   'messages': {'error': error, 'sucesss': success}})


@require_http_methods(["GET", "POST"])
def user_login(request):
    remember_me_data = {
        "password": request.COOKIES.get('password'),
        "username": request.COOKIES.get('username')
    }
    if (request.user.is_authenticated):
        return redirect(reverse('subsections:home'))
    error = ''
    flag = "false"
    if request.method == 'POST':
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data

            user = authenticate(request, username=cd['login'], password=cd['password'])
            if user is None:
                user = authenticate(request, username=cd['login'], password=cd['password'])

            if user:
                if user.is_active:
                    check_black_list = BlacklistUser.objects.filter(user=user, on_login=True).first()
                    if not check_black_list:
                        login(request, user)
                        token, created = Token.objects.get_or_create(user=user)
                        token_expire_handler(request)
                        request.session['encryption_token'] = cd['password']
                        request.session.modified = True
                        MessagingRSA.create_rsa(request)
                        response = redirect(reverse('subsections:home'))
                        if user.first_login:
                            response = redirect(reverse('steps_form'))

                        if cd['remember_me']:
                            response.set_cookie('password', cd['password'])
                            response.set_cookie('username', cd['login'])

                        if user.first_login:
                            return response
                        return response
                    else:
                        error = 'Sayches suspends accounts which violate the Sayches Rules'
                        flag = "true"
                else:
                    error = 'Disabled account'
            else:
                error = 'Username or password does not match'
                flag = "true"
        else:
            error = 'Fill the username and password'
    else:
        login_form = UserLoginForm()
    return render(request, 'account/login.html',
                  {'form': login_form, 'error': error, "flag": flag, "remember_me_data": remember_me_data})

@login_required
@require_http_methods(["GET", "POST"])
def steps_form(request):
    user = request.user
    if not (user.first_login):
        return redirect(reverse('subsections:home'))
    profile = user.profile
    initial_dic = {}
    errors = ''

    if user.name:
        initial_dic['name'] = user.name

    if user.country:
        initial_dic['country'] = user.country.name

    if request.method == 'POST':
        steps_form = StepsForm(data=request.POST, files=request.FILES)

        if steps_form.is_valid():
            cd = steps_form.cleaned_data

            user.alias = cd['alias']
            user.country = request.POST.get('location')
            user.first_login = False
            user.save()

            if cd['image']:
                profile = Profile.objects.get(user=user)
                profile.photo = cd['image']
            profile.save()
            return redirect(reverse('subsections:home'))


        else:
            for error in steps_form.errors:
                errors += error

    else:
        steps_form = StepsForm(initial=initial_dic)

    context = {'steps_form': steps_form, 'bitcoin_address': get_bitcoin_address, "errors": errors}
    return render(request, 'account/steps_form/steps_form.html', context)


@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('subsections:home')
    return render(request, 'account/logout.html')

sayches/templates/base/base.html
<!doctype html>
{% load i18n %}
{% load static %}
{% load compress %}
<html lang="en" dir="ltr">
   <head>
      <noscript>
         <meta HTTP-EQUIV="refresh" content=0;url="/">
      </noscript>
      {% include "base/meta_tags.html" %}
      {% block othermeta %} {% endblock %}
      <link href="{% static 'lib/css/bootstrap.min.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'lib/css/4.0.0-bootstrap.min.css' %}">
      <link href="{% static 'lib/css/select2.min.css' %}" rel="stylesheet" />
      <link href="{% static 'lib/css/pretty-checkbox.min.css' %}" rel="stylesheet" />
      <link rel="stylesheet" href="{% static 'lib/webfonts/remixicon/remixicon.css' %}">
      <link rel="icon" href="{% static 'assets/images/saychesLogo/favicon.ico' %}" />
      {% compress css %}
      <link href="{% static 'lib/css/fontface.css' %}" rel="stylesheet">
      {% endcompress %}
      {% compress css %}
      <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
      {% endcompress %}
      {% compress css %}
      <link rel="stylesheet" href="{% static 'assets/css/keyframes.css' %}">
      {% endcompress %}
      {% compress css %}
      <link rel="stylesheet" href="{% static 'assets/css/media.css' %}">
      {% endcompress %}
      {% compress css %}
      <link rel="stylesheet" href="{% static 'assets/css/stylesheet.css' %}">
      {% endcompress %}
      <title>{% block title %}Sayches{% endblock %}</title>
   </head>
   <body>
      {% block head %}
      {% include "base/header/header.html" %}
      {% endblock head %}
      {% block modal %}{% endblock modal %}
      <main>
         <div class="up-btn"><i class="ri-arrow-up-s-line font-weight-bold"></i></div>
         <a href="{% url 'posts:post_like' %}" class="like_post_view d-none"></a>
         <a href="{% url 'posts:create_post' %}" class="create_post_view d-none"></a>
         <a href="{% url 'posts:pin_post' %}" class="pin-post-view d-none"></a>
         <a href="{% url 'users:notification_number' %}" class="notification_number_view_view d-none"></a>
         <a href="{% url 'users:mark_all_read' %}" class="mark_all_read_view d-none"></a>
         <a href="{% url 'users:notify_read' %}" class="notify_read_view d-none"></a>
         <a href="{% url 'users:admin_notify_read' %}" class="admin_notify_read_view d-none"></a>
         <a href="{% url 'posts:post_read' %}" class="post_read_view d-none"></a>
         <a href="{% url 'message:chat_header_data' %}" class="chat_header_view d-none"></a>
         <a href="{% url 'message:admin_messages_content_data' %}" class="admin_messages_content_view d-none"></a>
         <a href="{% url 'message:old_messages_content_data' %}" class="old_messages_content_data_view d-none"></a>
         <a href="{% url 'message:new_messages_content_data' %}" class="new_messages_content_data_view d-none"></a>
         <a href="{% url 'message:delete_chat' id=12345 %}" class="delete_chat_view d-none"></a>
         <a href="{% url 'message:create_message' %}" class="create_message_view d-none"></a>
         {% if close_site %}
         <br>
         <h2 class="span4 text-center font-weight-bold">{{ closing_text }}</h2>
         {% else %}
         {% block content %}
         {% endblock content %}
         {% endif %}
      </main>
      {% if request.path != "/feed" %}
      <footer>
         {% include "base/footer/footer.html" %}
      </footer>
      {% endif %}
      <script src="{%static 'lib/js/jquery.min.js' %}"></script>
      <script src="{%static 'lib/js/popper.min.js' %}"></script>
      <script src="{%static 'lib/js/bootstrap.min.js' %}"></script>
      <script src="{%static 'lib/js/select2.full.min.js' %}"></script>
      <script src="{%static 'lib/js/jquery.smartWizard.min.js' %}"></script>
      <script src="{% static 'lib/js/pace.min.js' %}"></script>
      <script language="javascript">var STATIC_URL = "{{ STATIC_URL|escapejs }}";</script>
      {% compress js %}
      <script src="{% static 'assets/js/script.js' %}"></script>
      {% endcompress %}
      {% compress js %}
      <script src="{%static 'assets/js/script-ajax2.js' %}"></script>
      {% endcompress %}
      {% compress js %}
      <script src="{% static 'assets/js/load-reacton.js' %}"></script>
      {% endcompress %}
      {% if backbtn %}
      <script>function goBack() { window.history.back(); }</script>
      {%endif%}
      {% block js %}
      {% endblock js %}
   </body>
</html>

sayches/templates/base/meta_tags.html
{% load static %}
<meta name="description" content="{% if profile.bio %}{{ profile.bio }}{% else %}Sayches is an anonymous platform designed to protect, defend, empower public-interest journalism and champion the free flow of information.{% endif %}" />
<meta property="og:site_name" content="Sayches" />
<meta property="og:image" content="{% if profile.photo_url %}{{ profile.photo_url }}{% else %}{% static 'assets/images/saychesLogo/sayches_3545x3545.png' %}{% endif %}" />
<meta property="og:description" content="{% if profile.bio %}{{ profile.bio }}{% else %}Sayches is an anonymous platform designed to protect, defend, empower public-interest journalism and champion the free flow of information.{% endif %}" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:description" content="{% if profile.bio %}{{ profile.bio }}{% else %}Sayches is an anonymous platform designed to protect, defend, empower public-interest journalism and champion the free flow of information.{% endif %}" />
<meta name="twitter:image" content="{% if profile.photo_url %}{{ profile.photo_url }}{% else %}{% static 'assets/images/saychesLogo/sayches_3545x3545.png' %}{% endif %}" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="theme-color" content="#F7941D">
<link rel="canonical" href="{{ request.get_full_path }}" />

sayches/templates/base/outer_base.html
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="theme-color" content="#F7941D">
<link rel="stylesheet" href="{% static 'lib/css/4.0.0-bootstrap.min.css' %}">
<link href="{% static 'lib/css/fontface.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'lib/webfonts/remixicon/remixicon.css' %}">
<link href="{% static 'lib/css/pretty-checkbox.min.css' %}" rel="stylesheet" />
<link href="{% static 'lib/css/select2.min.css' %}" rel="stylesheet" />
<link rel="icon" href="{% static 'assets/images/saychesLogo/favicon.ico' %}" />
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/keyframes.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/media.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/stylesheet.css' %}">

sayches/templates/base/reminders.html
{% load static %}
{%if request.session.rate_limiter_post == True %}
<div class="alert secondary-colour primary-b-red f-s-14 pa-5 text-center mb-0">
   <strong>Alert!</strong> Consecutive posting is NOT allowed. Please try again in an hour
   <a class="float-right" href="{% url 'subsections:remove_alert' %}"><img src="{% static 'assets/images/icons/svgIcons/close_100x100.svg' %}" alt="Close" class="custom-ex"></a>
</div>
{%endif%}

sayches/templates/base/suspended.html
{% load static %}
{% if is_block_user %}
<h4 class='text-center font-weight-bold'>Account suspended</h4>
<p class='text-center'>Sayches suspends accounts which violate the Sayches Rules</p>
{% endif %}
{% if user.disposable and not is_block_post  %}
<h4 class='text-center font-weight-bold'>Why do you need settings?</h4>
<p class='text-center'>Trash account does not have access to the settings</p>
{% endif %}