config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView, TemplateView
from django_otp.admin import OTPAdminSite
from users.models import User
from django.contrib.sitemaps.views import sitemap
from sayches.subsections.sitemaps import HomeStaticViewSitemap
from sayches.users.sitemaps import UserProfileStaticViewSitemap
from django.views.static import serve
import os
from rest_framework.authtoken.views import obtain_auth_token
from sayches.subsections.rss import NewsroomFeed

class OTPAdmin(OTPAdminSite):
    pass

from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")}, name="404"
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


sitemaps = {
            "home_static": HomeStaticViewSitemap,
            "users_static":UserProfileStaticViewSitemap,
            }

ADMIN_URL = os.environ.get('ADMIN_PATH')

urlpatterns += [
                   path("", include("subsections.urls", namespace="subsections")),
                   path("", RedirectView.as_view(pattern_name='subsections:home', permanent=False)),
                   path(ADMIN_URL, admin.site.urls),
                   path("", include("sign.urls")),
                   path("", include("users.urls", namespace="profile")),
                   path("", include("posts.urls", namespace="posts")),
                   path("", include("ads.urls", namespace="ads")),
                   path("messages/", include("message.urls", namespace="message")),
                   path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                   path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
                   path("api/", include("api.urls")),
                   path('auth/', obtain_auth_token),
                   path('newsroom/rss/', NewsroomFeed()),
]

DEBUG = os.environ.get('DEBUG')

if eval(DEBUG) == False:
    admin.site.__class__ = OTPAdminSite
admin.site.site_header = "Administration Area"
admin.site.site_title = "Sayches Admin Portal"
handler404 = 'sayches.custom_views.handler404'

sayches/ads/urls.py
from django.urls import path

from . import views

app_name = "ads"

urlpatterns = [
    path("ads/invoice/<str:invoice_number>", views.ad_invoice, name="ad-invoice"),
    path("ad_click/<str:slug>", views.ad_clicks, name="ad_click"),
]

sayches/api/urls.py
from django.conf import settings
from django.urls import path, include
from rest_framework import routers

from .views import *

if settings.DEBUG:
    router = routers.DefaultRouter()
else:
    router = routers.SimpleRouter()

############# # Post APIs # #############
router.register('post', PublicPostViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

sayches/message/urls.py
from django.urls import path

from . import views

app_name = "message"

urlpatterns = [
    path("", views.chat_inbox, name="inbox"),
    path("inbox/delete/<int:id>/", views.delete_chat, name="delete_chat"),
    path("create_message/", views.create_messages, name="create_message"),
    path("chat_data/", views.chat_data, name="chat_data"),
    path("chat_header_data/", views.chat_header_data, name="chat_header_data"),
    path("chat_content_data/", views.old_messages_content_data, name="old_messages_content_data"),
    path("ad_chat_content_data/", views.admin_messages_content_data, name="admin_messages_content_data"),
    path("new_messages_content_data/", views.new_messages_content_data, name="new_messages_content_data"),
    path("search-users-and-chats/", views.search_for_users_and_chats, name="search-users-and-chats"),
    path("chat/<str:username>/", views.start_chat_with_user, name="chat-specfic-user"),
    path("user/json/<str:username>/", views.get_json_user, name="get-json-user"),

]

sayches/sign/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.user_login, name='login'),
    path('steps_form/', views.steps_form, name='steps_form'),
    path('logout/', views.logout_view, name='logout'),
]

sayches/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('<int:id>/', views.profile_detail, name="profile"),
    path('settings', views.profile_update, name="profile_update"),
    path('update/nick', views.UpdateNickView.as_view(), name="profile_nickname"),
    path('update/toggle', views.UpdateToggleView.as_view(), name="profile_toggles"),
    path('u/<str:username>', views.profile_detail_name, name="profile_name"),
    path('forget/<str:username>', views.forget_user, name='forget-user'),
    path('set-or-remove-bell/<str:username>/', views.set_or_remove_bell_for_user, name="set-or-remove-bell"),
    path('ping-user/<str:username>', views.ping_user, name="ping-user"),
    path('pong-user/<int:id>/', views.pong_user, name="pong-user"),
    path('report_user', views.report_user, name="report_user"),
    path("notifications/notifications_counter", views.notification_number, name="notification_number"),
    path("notifications/mark_all", views.mark_all_read, name="mark_all_read"),
    path("notifications/notify_read", views.notify_read, name="notify_read"),
    path("notifications/admin_notify_read", views.admin_notify_read, name="admin_notify_read"),
    path("notifications/notifications_reload/", views.notifications_reload, name="notifications_reload"),
    path("export/<str:username>", views.export_my_data, name="export_my_data"),
    path('search/user', views.search_user, name='search-user'),
]

sayches/sudo/models.py
from django.db import models
from users.models import BaseModel


class CloseWebsite(BaseModel):
    close_site = models.BooleanField(default=False)
    closing_text = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.closing_text

    def delete(self):
        self.close_site = False
        self.save()

    class Meta:
        verbose_name_plural = "Close Website"


class VersionNumber(BaseModel):
    version_no = models.CharField(max_length=25, null=True, blank=True)
    show_beta_icon = models.BooleanField(default=False)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Versioning"


class CloseRegistration(BaseModel):
    close_registration = models.BooleanField(default=False)
    custom_error_message = models.TextField(null=True, blank=False)

    class Meta:
        verbose_name_plural = "Close Registration"

class BitcoinAddress(BaseModel):
    address = models.CharField(null=True, blank=False, max_length=45, unique=True)
    expired = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.address

    class Meta:
        verbose_name_plural = "Bitcoin Addresses"

sayches/message/forms.py
from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']


class MessageFromProfile(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']

sayches/ads/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from subsections.models import Ads

from .models import CreateAds, Vouchers


def targeted_ads(request):
    ad = CreateAds.objects.filter(Q(location=request.user.country) |
                                  Q(target_all_users=True) |
                                  Q(target_user_list=request.user)).order_by('?').first()
    return ad


@login_required
def ad_invoice(request, invoice_number):
    ads = Ads.objects.get(slug=invoice_number)
    try:
        ads_owner = Ads.objects.get(user=request.user)
    except:
        ads_owner = None
    if request.user != ads.user:
        return redirect('subsections:home')
    context = {
        "ads": ads,
        "ads_owner": ads_owner,
    }
    return render(request, 'ads/invoice.html', context)


def voucher_discount(voucher, ads):
    discount_percentage = voucher.discount_percentage
    discount_amount = discount_percentage / 100 * ads.ad_price
    amount_due = ads.ad_price - discount_amount
    ads.amount_due = amount_due
    ads.discount_amount = discount_amount
    ads.discount = discount_percentage
    ads.save()
    return discount_percentage, amount_due


def ad_period(ads):
    start_date = ads.ad_start_date
    end_date = ads.ad_end_date
    number_of_days = (end_date - start_date).days
    return number_of_days


def ad_clicks(request, slug):
    if request.is_ajax():
        try:
            ad = Ads.objects.get(status="1", slug=slug)
            ad.clicks.add(request.user)
            ad.save()
        except:
            return JsonResponse({'success': 'false'})
        return JsonResponse({'success': 'true'})
    return HttpResponseBadRequest()


def validate_voucher(voucher_code, user, ad_plan):
    if not voucher_code:
        return
    vouchers = Vouchers.objects.filter(voucher_code=voucher_code, expired=False)

    if not vouchers.exists():
        return False

    voucher = vouchers.first()
    try:
        if voucher.end_date <= datetime.date.today():
            vouchers.update(expired=True)
    except:
        pass

    if voucher.is_expired or not voucher.is_valid(user, ad_plan):
        return False

    return voucher

sayches/api/views.py
from posts.models import Post
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .serializers import *


############# # Post APIs # #############


class PublicPostViewSet(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    serializer_class = PublicPostSerializer
    queryset = Post.objects.all()
    http_method_names = ['get']
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        queryset = Post.objects.filter(user=self.request.user)
        return queryset

sayches/sign/views.py
from datetime import timedelta, datetime

import requests
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from message.crypto import MessagingRSA
from rest_framework.authtoken.models import Token
from sign.utils import token_expire_handler
from subsections.views import get_bitcoin_address
from sudo.models import CloseRegistration
from users.models import BlacklistUser
from users.models import Profile
from users.models import User

from .forms import UserRegistrationForm, UserLoginForm, StepsForm


@require_http_methods(["GET", "POST"])
def signup(request):
    if (request.user.is_authenticated):
        return redirect(reverse('subsections:home'))
    error = ''
    success = ''
    flag = "false"
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid():
            cd = user_form.cleaned_data
            new_user = user_form.save(commit=False)
            new_user.username = cd['user_hash']
            new_user.set_password(cd['password'])
            new_user.first_login = True
            new_user.is_active = True
            if cd['disposable']:
                new_user.disposable = True
            new_user.save()
            Profile.objects.create(user=new_user)
            user = authenticate(request, username=cd['user_hash'], password=cd['password'])
            login(request, user)
            token, created = Token.objects.get_or_create(user=user)
            token_expire_handler(request)
            request.session['encryption_token'] = cd['password']
            request.session.modified = True
            MessagingRSA.create_rsa(request)
            if user.first_login:
                response = redirect(reverse('steps_form'))
                return response
            return redirect(reverse('login'), {'new_user': new_user})
        else:
            flag = "true"
    else:
        user_form = UserRegistrationForm()

    sayches_customization = CloseRegistration.objects.filter(close_registration=True).first()
    return render(request, 'account/signup.html', {'user_form': user_form,
                                                   'flag': flag,
                                                   'sayches_customization': sayches_customization,
                                                   'messages': {'error': error, 'sucesss': success}})


@require_http_methods(["GET", "POST"])
def user_login(request):
    remember_me_data = {
        "password": request.COOKIES.get('password'),
        "username": request.COOKIES.get('username')
    }
    if (request.user.is_authenticated):
        return redirect(reverse('subsections:home'))
    error = ''
    flag = "false"
    if request.method == 'POST':
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data

            user = authenticate(request, username=cd['login'], password=cd['password'])
            if user is None:
                user = authenticate(request, username=cd['login'], password=cd['password'])

            if user:
                if user.is_active:
                    check_black_list = BlacklistUser.objects.filter(user=user, on_login=True).first()
                    if not check_black_list:
                        login(request, user)
                        token, created = Token.objects.get_or_create(user=user)
                        token_expire_handler(request)
                        request.session['encryption_token'] = cd['password']
                        request.session.modified = True
                        MessagingRSA.create_rsa(request)
                        response = redirect(reverse('subsections:home'))
                        if user.first_login:
                            response = redirect(reverse('steps_form'))

                        if cd['remember_me']:
                            response.set_cookie('password', cd['password'])
                            response.set_cookie('username', cd['login'])

                        if user.first_login:
                            return response
                        return response
                    else:
                        error = 'Sayches suspends accounts which violate the Sayches Rules'
                        flag = "true"
                else:
                    error = 'Disabled account'
            else:
                error = 'Username or password does not match'
                flag = "true"
        else:
            error = 'Fill the username and password'
    else:
        login_form = UserLoginForm()
    return render(request, 'account/login.html',
                  {'form': login_form, 'error': error, "flag": flag, "remember_me_data": remember_me_data})

@login_required
@require_http_methods(["GET", "POST"])
def steps_form(request):
    user = request.user
    if not (user.first_login):
        return redirect(reverse('subsections:home'))
    profile = user.profile
    initial_dic = {}
    errors = ''

    if user.name:
        initial_dic['name'] = user.name

    if user.country:
        initial_dic['country'] = user.country.name

    if request.method == 'POST':
        steps_form = StepsForm(data=request.POST, files=request.FILES)

        if steps_form.is_valid():
            cd = steps_form.cleaned_data

            user.alias = cd['alias']
            user.country = request.POST.get('location')
            user.first_login = False
            user.save()

            if cd['image']:
                profile = Profile.objects.get(user=user)
                profile.photo = cd['image']
            profile.save()
            return redirect(reverse('subsections:home'))


        else:
            for error in steps_form.errors:
                errors += error

    else:
        steps_form = StepsForm(initial=initial_dic)

    context = {'steps_form': steps_form, 'bitcoin_address': get_bitcoin_address, "errors": errors}
    return render(request, 'account/steps_form/steps_form.html', context)


@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('subsections:home')
    return render(request, 'account/logout.html')

sayches/templates/profile/dropdown.html
{% load static %}
{% if current_user and request.user !=  profile.user %}
<div class="sec-box">
   <div class="profile-dropdown ">
      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
         aria-expanded="false">
      <i class="ri-more-2-fill" pop-attr=""></i>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
         {% if profile.disable_ping == False %}
         <a id="ping" class="dropdown-item {% if not today_ping %}ping-btn{% else %}disable{% endif %}" href="#" {% if today_ping %}disabled {% endif %}>Ping</a>
         {% endif %}
         <a id="bellNotification" class="dropdown-item" title= "Make sure you never miss updates from your favourite accounts by turning on the ringing bell to be notified of new posts.">
         <span id="bell_notification" style="display:{% if belled %}block{%else%}none{% endif %}; cursor: pointer" class="primary-red" onclick="updateBellNotificaion()">UnWatch</span>
         <span id="unbell_notification" style="display:{% if belled %}none{%else%}block{% endif %}; cursor: pointer" onclick="updateBellNotificaion()">Watch</span>
         </a>
         {% if profile.disable_messages == False %}
         <a href="{% url 'message:chat-specfic-user' profile.user.username %}" class="dropdown-item">
         Message
         </a>
         {% endif %}
         <a class="dropdown-item" data-toggle="Report-popup" onclick="$('.option-popup-box').addClass('d-flex')" href="#">Report</a>
      </div>
   </div>
</div>
{% endif %}
</div>

sayches/templates/profile/profile.html
{% extends 'base/base.html' %}
{% load static %}
{% load core_extras %}
{% load tz %}
{% load humanize %}
{% block othermeta %}
<meta property="og:title" content='Sayches / {{ user.name }} ({{ profile.user.username }})' />
<meta name="twitter:title" content='Sayches / {{ user.name }} ({{ profile.user.username }})'>
{% if user.profile.bio %}
<meta name="description" content="{% if user.profile.bio %}{{ user.profile.bio }}{% endif %}" />
<meta property="og:description" content="{% if user.profile.bio %}{{ user.profile.bio }}{% endif %}" />
<meta name="twitter:description" content="{% if user.profile.bio %}{{ user.profile.bio }}{% endif %}" />
{% endif %}
{% endblock %}
{% block title %}Sayches / {{ user.name }} ({{ profile.user.username }}){% endblock %}
{% block content %}
<div class="main-sec">
   <div class="container">
      <div class="row justify-content-center">

         <div class="col-lg-8">
            {% include "profile/profile_section.html" %}
            {% if request.user == profile.user %}
            {%include 'feed/textarea/create_post.html'%}
            {% endif %}
            {% if not is_block_post %}
            {%include 'profile/sort_by.html'%}
            <div class="main-post-box"></div>
            {% else %}
            {% include "base/suspended.html" %}
            {% endif %}
            <div id="loadPostIconId" class="spinner-border"></div>
            <div class="last-post">Last updated: {{ last_post_time|naturaltime }}</div>
            <div class="overlay-box"></div>
            {%include 'feed/popup.html'%}
         </div>

         {% include 'profile/report.html' %}
      </div>
   </div>
</div>
{% endblock content %}
{% block js %}
<script>
   $.ajaxSetup({
     headers: {
         "X-CSRFToken": '{{ csrf_token }}'
     }
   });
   
   var uINum = "{% url 'users:profile' profile.id %}"
   var setOrRemoveBell = "{% url 'users:set-or-remove-bell' profile.user.username %}"
   var pingUsername = "{% url 'users:ping-user' profile.user.username %}"
</script>
<script src="{% static 'assets/js/profile.js' %}"></script>
<script src="{% static 'assets/js/load-reacton.js' %}"></script>
{% endblock js %}

sayches/templates/profile/profile_section.html
{% load static %}
{% load short_number %}
<div class="profile-section">
<div class="info-box profile-profile-img">
   <div class="profile-img">
      <img alt="Profile Picture" src="{{ profile.photo_url }}" class="img-fluid">
   </div>
   <div class="profile-txt">
      <h3 class="font-weight-bold f-s-18 text-truncate-150-media">{{ user.get_name_or_username|escapejs }}</h3>
      <div class="nav-box">
         <p class="profile-p parag">{{ user.user_hash }}</p>
            <small class="validation {{ verification }}">
               {{ verification }}
               </small>
               {% if user.disposable %}<small class="Disposable validation">Disposable</small>
               {% else %}
               {% if not user.lost_virginity %}<small class="Virgin validation">Virgin</small>{% endif %}
               {% endif %} 
            {% if user.warrant_canary %}
            <button type="button" class="btn profile-btn" data-container="body" data-toggle="popover" data-placement="top"
               data-content="Sayches has not been served with a secret government subpoena to obtained access to {{ user.user_hash }} information or records. Watch very closely for the removal of this sign.">
            <img src="{% static 'assets/images/avatars/warrantCanary.svg' %}" alt="Warrant Canary" class="warrant-icon">
            </button>{% endif %}
      </div>
   </div>
</div>
<div class="main-box profile-box">
   <div class="follow-box">
      <div class="first-box {% if current_user and request.user ==  profile.user %}d-flex{% else %}profile-block{% endif %}">
         <span class="parag follow-p"><span>{{ user_total_posts|short_number }}</span>BLOWS</span>
         <span class="parag follow-p"><span>{{user.profile_age}}</span>DAYS</span>
         {% if user.country %} <span class="parag follow-p"><span><img src="{{user.country.flag}}" alt="Country"></span>{{ user.country.name|upper}}</span>{% endif %}
      </div>
      {% include 'profile/dropdown.html' %}
      <br>
      <p class="font-weight-bold f-s-13 text-center">{{ profile.bio|escapejs }}</p>
   </div>
</div>

sayches/templates/profile/report.html
{% load static %}
{% load core_extras %}
<div class="option-popup-box option-p parag"  data-id="Report-popup">
<div class="option-popup">
<div class="popup-heading">
   <h3 class="font-weight-bold f-s-17">Report a violation</h3>
   <img alt="Close" src="{% static 'assets/images/icons/svgIcons/close_100x100.svg' %}" class="popup-exit">
</div>
<div class="popup-body text-left">
   {% if not check_user_report %}
   <form onsubmit="reportAUser(event)" id="reportuserForm">
      {% csrf_token %}
      <input type="hidden" name="user" value="{{profile.user}}" />
      <div class="form-group">
         <p><U>Report an account for:</U></p>
         <div>
            <input type="radio" id="reason_1" name="reason" value="Civic integrity" Checked />
            <label for="reason_1">&nbsp  Civic integrity</label><br>
            <input type="radio" id="reason_2" name="reason" value="Copyright infringement / DMCA takedown and counter notice"/>
            <label for="reason_2">Copyright infringement / DMCA takedown and counter notice</label><br>
            <input type="radio" id="reason_3" name="reason"  value="Cyberbullying"/>
            <label for="reason_3">&nbsp Cyberbullying</label><br>
            <input type="radio" id="reason_4" name="reason"  value="Harassment, hateful or abusive"/>
            <label for="reason_4">&nbsp Harassment, hateful or abusive</label><br>
            <input type="radio" id="reason_5" name="reason"  value="Hate speech"/>
            <label for="reason_5">&nbsp Hate speech</label><br>
            <input type="radio" id="reason_6" name="reason" value="Illegal or certain regulated goods or services"/>
            <label for="reason_6">&nbsp Illegal or certain regulated goods or services</label><br>
            <input type="radio" id="reason_7" name="reason" value="Impersonation / Notice of trademark violation"/>
            <label for="reason_7">&nbsp Impersonation / Notice of trademark violation</label><br>
            <input type="radio" id="reason_8" name="reason"  value="Legal request for content removal"/>
            <label for="reason_8">&nbsp Legal request for content removal</label><br>
            <input type="radio" id="reason_9" name="reason" value="Multiple policy violations"/>
            <label for="reason_9">&nbsp Multiple policy violations</label><br>
            <input type="radio" id="reason_10" name="reason"  value="Nudity, sexual or pornography"/>
            <label for="reason_10">&nbsp Nudity, sexual or pornography</label><br>
            <input type="radio" id="reason_11" name="reason"  value="Private information"/>
            <label for="reason_11">&nbsp Private information</label><br>
            <input type="radio" id="reason_12" name="reason" value="Promoting suicide or self-harm"/>
            <label for="reason_12">&nbsp Promoting suicide or self-harm</label><br>
            <input type="radio" id="reason_13" name="reason" value="Spam, misleading and scams"/>
            <label for="reason_13">&nbsp Spam, misleading and scams</label><br>
            <input type="radio" id="reason_14" name="reason"  value=" Terrorism/violent extremism"/>
            <label for="reason_14">&nbsp  Terrorism/violent extremism</label><br>
            <input type="radio" id="reason_15" name="reason" value="Violence"/>
            <label for="reason_15">&nbsp Violence</label><br>
            <div class="form-group">
               <p><input required type="checkbox" id="check_1" onclick="checkBox_Ticked_OR_Not()" class="termCheck" name="terms_and_conditions_1" value="terms_and_conditions"> I understand that Sayches may provide third parties, for example the reported user with details of this report, such as the reported content. Your contact information, like your email address, will not be disclosed.</label><br></p>
               <p><input required type="checkbox" id="check_2" onclick="checkBox_Ticked_OR_Not()" class="termCheck" name="terms_and_conditions_2" value="terms_and_conditions"> I declare under penalty of perjury that all of the information provided above is accurate.</br></p>
            </div>
            <div class="btn-center-box">
               <button btn-input="QuoteInput" onclick="addClassToDiv()" id="reportButton" type="submit" class="post-btn primary-button prevent_multiple">Submit</button>
            </div>
   </form>
   {% else %}
   <form >
   <h6>Yor have alreday reported this user.</h6>
   </form>
   {% endif %}
   </div>
   </div>
</div>

sayches/templates/profile/report_user_email.html
Hello {{ username }},
We have received a complaint regarding your account, for the following reason: {{reason}}.
{% if action == "Account has been suspended" %}
Your account has been suspended from Sayches. We have investigated your account and could not identify any violations of the Sayches Rules or applicable law.
Be sure to read up on the Sayches ToS to make sure you understand the rules for participating on Sayches. This is an automated message; responses will not be received.
{% elif action == "No action taken" %}
We have investigated your account and could not identify any violations of the Sayches Rules or applicable law. Accordingly, we have not taken any action at this time.
{% elif action == "Post was removed" %}
We have investigated your account and identified a violations of the Sayches Rules or applicable law. Accordingly, we have removed your post from your account.
{% endif %}
Sincerely,
Sayches

sayches/templates/profile/sort_by.html
{% load static %}
<div class="sort-by">
   <hr>
   <div class="sort-by-dropdown">
      <button class="select-sort-type">Sort By: <b><span id="current-sort-type">Recent</span></b>
      <i class="ri-arrow-down-s-fill"></i>
      </button>
      <div class="sort-type-list" id="sort-type-list">
         <a href="javascript:void(0)" onclick=loadPosts('recent',1)> Recent </a>
         <a href="javascript:void(0)" onclick=loadPosts('oldest',1)> Oldest </a>
      </div>
   </div>
</div>