config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView, TemplateView
from django_otp.admin import OTPAdminSite
from users.models import User
from django.contrib.sitemaps.views import sitemap
from sayches.subsections.sitemaps import HomeStaticViewSitemap
from sayches.users.sitemaps import UserProfileStaticViewSitemap
from django.views.static import serve
import os
from rest_framework.authtoken.views import obtain_auth_token
from sayches.subsections.rss import NewsroomFeed

class OTPAdmin(OTPAdminSite):
    pass

from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")}, name="404"
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


sitemaps = {
            "home_static": HomeStaticViewSitemap,
            "users_static":UserProfileStaticViewSitemap,
            }

ADMIN_URL = os.environ.get('ADMIN_PATH')

urlpatterns += [
                   path("", include("subsections.urls", namespace="subsections")),
                   path("", RedirectView.as_view(pattern_name='subsections:home', permanent=False)),
                   path(ADMIN_URL, admin.site.urls),
                   path("", include("sign.urls")),
                   path("", include("users.urls", namespace="profile")),
                   path("", include("posts.urls", namespace="posts")),
                   path("", include("ads.urls", namespace="ads")),
                   path("messages/", include("message.urls", namespace="message")),
                   path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                   path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
                   path("api/", include("api.urls")),
                   path('auth/', obtain_auth_token),
                   path('newsroom/rss/', NewsroomFeed()),
]

DEBUG = os.environ.get('DEBUG')

if eval(DEBUG) == False:
    admin.site.__class__ = OTPAdminSite
admin.site.site_header = "Administration Area"
admin.site.site_title = "Sayches Admin Portal"
handler404 = 'sayches.custom_views.handler404'

sayches/ads/urls.py
from django.urls import path

from . import views

app_name = "ads"

urlpatterns = [
    path("ads/invoice/<str:invoice_number>", views.ad_invoice, name="ad-invoice"),
    path("ad_click/<str:slug>", views.ad_clicks, name="ad_click"),
]

sayches/api/urls.py
from django.conf import settings
from django.urls import path, include
from rest_framework import routers

from .views import *

if settings.DEBUG:
    router = routers.DefaultRouter()
else:
    router = routers.SimpleRouter()

############# # Post APIs # #############
router.register('post', PublicPostViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

sayches/sign/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.user_login, name='login'),
    path('steps_form/', views.steps_form, name='steps_form'),
    path('logout/', views.logout_view, name='logout'),
]

sayches/subsections/urls.py
from django.urls import path

from . import views

app_name = "subsections"

urlpatterns = [
    path("feed", views.home, name="home"),
    path("docs/", views.docs, name="docs"),
    path("docs/<str:slug>", views.single_docs, name="single_docs"),
    path("newsroom", views.newsroom, name="news"),
    path("newsroom/<str:slug>", views.article, name="article"),
    path("help", views.help, name="help"),
    path("remove_alert", views.remove_alert, name="remove_alert"),
    path('ads/', views.ads_step_one, name="ads"),
    path('ads/design/<str:ads_slug>/', views.ads_step_two, name="ads-step-two"),
    path('ads/plan/<str:ads_slug>/', views.ads_step_three, name="ads-step-three"),
    path('ads/checkout/<str:ads_slug>/', views.ads_step_four, name="ads-step-four"),
]

sayches/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('<int:id>/', views.profile_detail, name="profile"),
    path('settings', views.profile_update, name="profile_update"),
    path('update/nick', views.UpdateNickView.as_view(), name="profile_nickname"),
    path('update/toggle', views.UpdateToggleView.as_view(), name="profile_toggles"),
    path('u/<str:username>', views.profile_detail_name, name="profile_name"),
    path('forget/<str:username>', views.forget_user, name='forget-user'),
    path('set-or-remove-bell/<str:username>/', views.set_or_remove_bell_for_user, name="set-or-remove-bell"),
    path('ping-user/<str:username>', views.ping_user, name="ping-user"),
    path('pong-user/<int:id>/', views.pong_user, name="pong-user"),
    path('report_user', views.report_user, name="report_user"),
    path("notifications/notifications_counter", views.notification_number, name="notification_number"),
    path("notifications/mark_all", views.mark_all_read, name="mark_all_read"),
    path("notifications/notify_read", views.notify_read, name="notify_read"),
    path("notifications/admin_notify_read", views.admin_notify_read, name="admin_notify_read"),
    path("notifications/notifications_reload/", views.notifications_reload, name="notifications_reload"),
    path("export/<str:username>", views.export_my_data, name="export_my_data"),
    path('search/user', views.search_user, name='search-user'),
]

sayches/ads/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from subsections.models import Ads

from .models import CreateAds, Vouchers


def targeted_ads(request):
    ad = CreateAds.objects.filter(Q(location=request.user.country) |
                                  Q(target_all_users=True) |
                                  Q(target_user_list=request.user)).order_by('?').first()
    return ad


@login_required
def ad_invoice(request, invoice_number):
    ads = Ads.objects.get(slug=invoice_number)
    try:
        ads_owner = Ads.objects.get(user=request.user)
    except:
        ads_owner = None
    if request.user != ads.user:
        return redirect('subsections:home')
    context = {
        "ads": ads,
        "ads_owner": ads_owner,
    }
    return render(request, 'ads/invoice.html', context)


def voucher_discount(voucher, ads):
    discount_percentage = voucher.discount_percentage
    discount_amount = discount_percentage / 100 * ads.ad_price
    amount_due = ads.ad_price - discount_amount
    ads.amount_due = amount_due
    ads.discount_amount = discount_amount
    ads.discount = discount_percentage
    ads.save()
    return discount_percentage, amount_due


def ad_period(ads):
    start_date = ads.ad_start_date
    end_date = ads.ad_end_date
    number_of_days = (end_date - start_date).days
    return number_of_days


def ad_clicks(request, slug):
    if request.is_ajax():
        try:
            ad = Ads.objects.get(status="1", slug=slug)
            ad.clicks.add(request.user)
            ad.save()
        except:
            return JsonResponse({'success': 'false'})
        return JsonResponse({'success': 'true'})
    return HttpResponseBadRequest()


def validate_voucher(voucher_code, user, ad_plan):
    if not voucher_code:
        return
    vouchers = Vouchers.objects.filter(voucher_code=voucher_code, expired=False)

    if not vouchers.exists():
        return False

    voucher = vouchers.first()
    try:
        if voucher.end_date <= datetime.date.today():
            vouchers.update(expired=True)
    except:
        pass

    if voucher.is_expired or not voucher.is_valid(user, ad_plan):
        return False

    return voucher

sayches/api/views.py
from posts.models import Post
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .serializers import *


############# # Post APIs # #############


class PublicPostViewSet(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    serializer_class = PublicPostSerializer
    queryset = Post.objects.all()
    http_method_names = ['get']
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        queryset = Post.objects.filter(user=self.request.user)
        return queryset

sayches/message/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_GET
from users.models import BlacklistUser

from .models import Chat, SaychesMessage
from .utils import (
    get_companion, create_chat, add_message_to_chat, get_chat_between_two_users,
    get_chat_dictionary_for_context, get_admin_chat_dictionary_for_context,
    get_chat_meta, get_message_dictionary)

User = get_user_model()


def redirect_if_messages_disabled(func):
    def wrapper(request, *args, **kwargs):
        try:
            disable_messages = request.user.profile.disable_messages
            if disable_messages:
                return redirect('subsections:home')
            else:
                return func(request, *args, **kwargs)
        except Exception as e:
            return redirect('subsections:home')

    return wrapper


@redirect_if_messages_disabled
@require_GET
def delete_chat(request, id):
    chat = get_object_or_404(Chat, id=id)
    chat.delete()
    return redirect('message:inbox')


@login_required
@redirect_if_messages_disabled
@require_GET
def chat_inbox(request):
    check_message_block = BlacklistUser.objects.filter(user=request.user, on_message=True).first()
    is_message_block = False
    if check_message_block:
        is_message_block = True
    context = {"is_message_block": is_message_block}
    return render(request, 'messages/inbox.html', context)


@redirect_if_messages_disabled
@require_POST
def create_messages(request):
    if request.is_ajax():
        msg_content = request.POST.get("msg_content")
        mate_user_id = request.POST.get("mate_user_id")
        if mate_user_id:
            mate_user = get_object_or_404(User, id=mate_user_id)
            chat_in_between = get_chat_between_two_users(
                request.user, mate_user).first()
            if chat_in_between:
                add_message_to_chat(chat_in_between, request.user, msg_content, mate_user, request)
                chat_in_between.is_read = False
                chat_in_between.save()
                return JsonResponse({'ok': 'ok'})
            else:
                chat = create_chat(request.user, mate_user)
                add_message_to_chat(chat, request.user, msg_content)
                return JsonResponse({'ok': 'ok'})
        return JsonResponse({'ok': 'no'})
    return HttpResponseBadRequest()


@require_GET
def chat_data(request):
    if request.is_ajax():
        user = request.user
        chat_context_list = []
        messages = SaychesMessage.objects.filter(user=user).order_by('created_at')
        if messages:
            chat_context_list.append(
                get_admin_chat_dictionary_for_context(messages))
        chats = user.chat_set.order_by('-time_of_last_msg')[:20]
        for chat in chats:
            mate_user = get_companion(user, chat)
            if mate_user is None:
                continue
            if mate_user.is_staff:
                continue
            if not mate_user.profile.disable_messages:
                chat_context_list.append(
                    get_chat_dictionary_for_context(mate_user, chat, request))
        return JsonResponse(chat_context_list, safe=False)
    return HttpResponseBadRequest()


@require_GET
def chat_header_data(request):
    if request.is_ajax():
        user = request.user
        chat_id = request.GET.get("chat_id")
        mate_user_id = request.GET.get("mate_user_id")
        if mate_user_id:
            mate_user = get_object_or_404(User, id=mate_user_id)
            chat_in_between = get_chat_between_two_users(user, mate_user).first()
            if chat_in_between:
                unread_messages = chat_in_between.chat_messages.filter(is_read=False)
                unread_messages.update(is_read=True)
                chat_in_between.is_read = True
                chat_in_between.save()
            return JsonResponse([get_chat_meta(mate_user)], safe=False)
        else:
            sayches_msgs = SaychesMessage.objects.filter(user=request.user)
            sayches_msgs.update(is_read=True)
            return JsonResponse([get_chat_meta()], safe=False)
    return HttpResponseBadRequest()


@require_GET
def admin_messages_content_data(request):
    if request.is_ajax():
        chat_content = []
        sayches_msgs = SaychesMessage.objects.filter(user=request.user)
        for msg in sayches_msgs:
            chat_content.append(get_message_dictionary(msg, "receive", request, is_admin=True))
        return JsonResponse(chat_content, safe=False)
    return HttpResponseBadRequest()


@require_GET
def old_messages_content_data(request):
    if request.is_ajax():
        chat_content = []
        user = request.user
        mate_user_id = request.GET.get("mate_user_id")
        if mate_user_id:
            mate_user = get_object_or_404(User, id=mate_user_id)
            chat_in_between = get_chat_between_two_users(user, mate_user).first()
            if chat_in_between:
                messages = chat_in_between.chat_messages.all()
                for msg in messages:
                    if msg.author == user:
                        msg_type = "send"
                    else:
                        msg_type = "receive"
                    chat_content.append(get_message_dictionary(msg, msg_type, request))
        return JsonResponse(chat_content, safe=False)
    return HttpResponseBadRequest()


@require_GET
def new_messages_content_data(request):
    if request.is_ajax():
        chat_content = []
        user = request.user
        mate_user_id = request.GET.get("mate_user_id")
        if mate_user_id:
            mate_user = get_object_or_404(User, id=mate_user_id)
            chat_in_between = get_chat_between_two_users(user, mate_user)
            chat = chat_in_between.first()
            if chat:
                messages = chat.chat_messages.filter(new=True)
                for msg in messages:
                    if msg.author == user:
                        msg_type = "send"
                    else:
                        msg_type = "receive"
                    msg.new = False
                    msg.save()
                    chat_content.append(get_message_dictionary(msg, msg_type))
        return JsonResponse(chat_content, safe=False)
    return HttpResponseBadRequest()


@require_GET
def search_for_users_and_chats(request):
    if request.is_ajax():
        chat_context_list = []
        key = request.GET.get('key', None)
        if key:
            filtered_users = User.objects.filter(
                username__icontains=key, is_staff=False)[:20]
            for user in filtered_users:
                if not user.profile.disable_messages:
                    chat_in_between = get_chat_between_two_users(
                        request.user, user).first()
                    chat_context_list.append(
                        get_chat_dictionary_for_context(user, chat_in_between))
            if key.lower() in 'sayches':
                messages = SaychesMessage.objects.filter(
                    user=request.user).order_by('created_at')
                if messages:
                    chat_context_list.append(
                        get_admin_chat_dictionary_for_context(messages))
        return JsonResponse(chat_context_list, safe=False)
    return HttpResponseBadRequest()


@redirect_if_messages_disabled
@require_GET
def start_chat_with_user(request, username):
    user = User.objects.get(username=username)
    if user.profile.disable_messages:
        return redirect('subsections:home')
    context = {"mate_username": username}
    return render(request, 'messages/inbox.html', context)


@require_GET
def get_json_user(request, username):
    if request.is_ajax():
        mate_user = get_object_or_404(User, username=username)
        chat_in_between = get_chat_between_two_users(
            request.user, mate_user).first()
        mate_user_chat = get_chat_dictionary_for_context(mate_user, chat_in_between)
        return JsonResponse(mate_user_chat)
    return HttpResponseBadRequest()

sayches/templates/feed/feed.html
{% extends 'base/base.html' %}
{% load tz %}
{% load static %}
{% block title %}Sayches{% if request.user.is_authenticated %} / Feed{% endif %}{% endblock %}
{% block othermeta %}
<meta property="og:title" content="Sayches / Feed" />
<meta name="twitter:title" content="Sayches / Feed">
{% endblock %}
{% block content %}
<div class="main-sec">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        {% if request.user.is_authenticated %}
        {%include 'feed/textarea/create_post.html'%}
        {% endif %}
        {% if not is_block_post %}
        <div class="sort-by" id="current-sort-type"></div>
        {% endif %}
        {% if not is_block_post %}
        <div class="main-post-box {% if not request.user.is_authenticated %}animation-content{% endif %}"></div>
        {% else %}
        {% include "base/suspended.html" %}
        {% endif %}
        <div id="loadPostIconId" class="spinner-border">
        </div>
        {%include 'feed/popup.html'%}
      </div>
      {%include 'feed/sidebar.html'%}
    </div>
  </div>
</div>
{% include "base/footer/cookie_banner.html" %}
{% if not request.user.is_authenticated %}
{% include 'base/footer/footer.html' %}
{% endif %}
{% endblock content %}
{% block js %}
<script>
  $.ajaxSetup({
      headers: {
          "X-CSRFToken": '{{ csrf_token }}'
      }
  });
  
  var postsData = "{% url 'posts:posts_data' %}";
  var newPostsData = "{% url 'posts:new_posts_data' %}";
</script>
<script src="{% static 'assets/js/feed.js' %}"></script>
<script src="{% static 'assets/js/load-reacton.js' %}"></script>
{% endblock js %}

sayches/templates/feed/popup.html
{% load tz %}
{% load static %}
<div class="overlay-box"></div>
<div class="link-popup main-popup">
   <img src="{% static 'assets/images/icons/svgIcons/close_100x100.svg' %}" class="custom-ex link-modal">
   <h3 class="popup-h">Heads up!</h3>
   <p class="popup-p parag">
      <span class="main-txt-pop"></span>
      <span class="msg-txt"></span>
      <span class="msg-txt2"></span>
      <span class="msg-link">
      </span>
   </p>
   <div class="btn-popup-box">
      <button type="button" class="btn-cancel heading link-modal" data-dismiss="modal"
         aria-label="Close">Cancel</button>
      <p class="btn-continue  heading"><a href="#">Continue</a></p>
   </div>
</div>

sayches/templates/feed/post_block.html
{% load static %}
<div class="option-popup-box" data-id="post-block">
   <div class="option-popup">
      <div class="popup-heading">
         <h3 class="font-weight-bold f-s-17">Your account has been blocked from posting</h3>
         <img src="{% static 'assets/images/icons/svgIcons/close_100x100.svg' %}" alt="Close" class="popup-exit">
      </div>
      <div class="popup-body">
         <p>This post can't be shared
         <p>
      </div>
   </div>
</div>

sayches/templates/feed/sidebar.html
{% load static %}
<div class="col-lg-4">
  <div class="custom-sidebar">
    <div class="main-box sidebar-box">
      <h2 class="font-weight-bold f-s-17">WHAT IS HAPPENING?</h2>
      {% for hashtag in hashtags %}
      <div class="mini-box custom-blue">
        <a href="{% url 'posts:search_hash' hashtag.explicit_name %}" class="overlay-link"></a>
        <div class="trend-img">
          <i class="ri-hashtag font-weight-bold"></i>
        </div>
        <div class="txt-box">
          <h3 class="heading mini-box-h text-truncate-200"><span class="minibox-explicitname">{{ hashtag.explicit_name }} </span><br><span class="minibox-explicitcounter">{% if hashtag.hashtag_counter > 100 %} Hullabaloo {% else %} Nothingburger{% endif %}</span></h3>
        </div>
      </div>
      {% empty %}
      <div class="mini-box custom-blue">
        <a href="#" class="overlay-link"></a>
        <div class="trend-img">
          <i class="ri-hashtag font-weight-bold"></i>
        </div>
        <div class="txt-box">
          <h3 class="heading mini-box-h">No Trends Yet</h3>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="main-box sidebar-box">
      <h2 class="font-weight-bold f-s-17">SUGGESTIONS FOR YOU</h2>
      {% for oneuser in users %}
      <div class="mini-box custom-blue">
        <a href="{% url 'users:profile_name' oneuser.user_hash %}" class="overlay-link"></a>
        <div class="follower-img">
          <img src="{{ oneuser.profile.photo_url }}" alt="Profile Picture">
        </div>
        <div class="txt-box">
          <h3 class="heading mini-box-h text-truncate-150"> {% if oneuser.name %} {{oneuser.name|escapejs}} {% else %} {{ oneuser.user_hash|escapejs }} {% endif %}</h3>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="main-box sidebar-box">
      <h2 class="font-weight-bold f-s-17">FLYER</h2>
      <div class="advertisement-box">
        {% if ad.image %}
        <a href="{{ad.link}}" target="_blank"><img onclick="addClick('{{ ad_slug }}')" src="{{ad.image.url}}" class="img-fluid" alt="Advertisement"></a>
        {% else %}
        <a href="#"><img alt="Advertisement" src="{% static 'assets/images/blanks/373x256.png' %}" class="img-fluid"></a>
        {% endif %}
      </div>
    </div>
    {% if request.user.is_authenticated %}
    <div class="main-box sidebar-box">
      <h2 class="font-weight-bold f-s-17">SITEMAP</h2>
      <ul class="sidebar-ul">
        <li class="sidebar-li"><a class="parag" href="{% url 'subsections:docs' %}"> Docs </a></li>
        <li class="sidebar-li"><a class="parag" href="{% url 'subsections:news' %}"> Newsroom </a></li>
        <li class="sidebar-li"><a class="parag" href="{% url 'subsections:ads' %}"> Ads </a></li>
        <li class="sidebar-li"><a class="parag" href="{% url 'subsections:help' %}"> Help </a></li>
      </ul>
      <p class="footer-p"><a href="#">Sayches © 2020-2022 {{ version_no }}
        </a>
      </p>
    </div>
    {% endif %}
  </div>
</div>
<script src="{% static 'assets/js/ads.js' %}"></script>